import { GoogleGenerativeAI } from "@google/generative-ai";

import { db } from "@/firebase/admin";
import { getRandomInterviewCover } from "@/lib/utils";

export const runtime = "nodejs";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { type, role, level, techstack, amount, userid } = body;

    // ---- Basic Validation ----
    if (!role || !level || !techstack || !amount || !userid) {
      return Response.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
    if (!apiKey) {
      throw new Error("Gemini API key not found in environment");
    }
    console.log("KEY PREFIX:", apiKey.slice(0, 6));

    // ---- Initialize Gemini ----
    const genAI = new GoogleGenerativeAI(apiKey);

    

    const model = genAI.getGenerativeModel({
      model: "gemini-3-flash-preview",
    });


    // ---- Generate Interview Questions ----
    const result = await model.generateContent(`
Prepare questions for a job interview.
The job role is ${role}.
The job experience level is ${level}.
The tech stack used in the job is: ${techstack}.
The focus between behavioural and technical questions should lean towards: ${type}.
The amount of questions required is: ${amount}.
Return ONLY a JSON array like:
["Question 1", "Question 2", "Question 3"]
Do not include any other text.
`);

    const text = result.response.text();

    // ---- Clean Gemini Output ----
    const cleanText = text.replace(/```json|```/g, "").trim();

    let parsedQuestions: string[] = [];

    try {
      parsedQuestions = JSON.parse(cleanText);
    } catch {
      const match = cleanText.match(/\[.*\]/s);
      if (match) {
        parsedQuestions = JSON.parse(match[0]);
      } else {
        throw new Error("Gemini returned invalid JSON");
      }
    }

    if (!parsedQuestions.length) {
      throw new Error("No questions generated by Gemini");
    }

    // ---- Prepare Firestore Document ----
    const interview = {
      role,
      type,
      level,
      techstack: techstack.split(",").map((t: string) => t.trim()),
      questions: parsedQuestions,
      userId: userid,
      finalized: true,
      coverImage: getRandomInterviewCover(),
      createdAt: new Date().toISOString(),
    };

    // ---- Save to Firestore ----
    await db.collection("interviews").add(interview);

    return Response.json({ success: true }, { status: 200 });
  } catch (error: any) {
    console.error("API Error:", error?.message || error);

    return Response.json(
      {
        success: false,
        error: error?.message || "Internal Server Error",
      },
      { status: 500 }
    );
  }
}
